from decimal import Decimal

DEFAULT_LARGE_DONATION_THRESHOLD = Decimal("1000000000")
DEFAULT_FREE_CONTRACT_THRESHOLD = Decimal("500000000")
DEFAULT_NEW_JOIN_WINDOW_DAYS = 14
DEFAULT_ALT_CORP_HISTORY_MAX_JOIN_LEAVE_DIFF_HOURS = 24
DEFAULT_CORP_OVERLAP_RULE1_MIN_CORPS = 1
DEFAULT_CORP_OVERLAP_RULE2_MIN_CORPS = 3
DEFAULT_CORP_OVERLAP_RULE3_MIN_CORPS = 5
DEFAULT_KILLMAIL_MAX_ATTACKER_COUNT = 0
DEFAULT_SUMMARY_LINK_EXPIRY_HOURS = 24
DEFAULT_ZKILL_THROTTLE_SECONDS = Decimal("0.10")
DEFAULT_ZKILL_KILL_PAGES = 3
DEFAULT_ZKILL_LOSS_PAGES = 3
DEFAULT_ZKILL_CAPITAL_KILL_PAGES = 5
DEFAULT_ZKILL_CAPITAL_LOSS_PAGES = 5

# Awox / friendly-fire detection defaults
DEFAULT_AWOX_MIN_DAMAGE_SHARE = Decimal("0.50")
DEFAULT_AWOX_LOOKBACK_DAYS = 180
DEFAULT_AWOX_LARGE_FLEET_ATTACKER_THRESHOLD = 10
DEFAULT_AWOX_SOLO_ATTACKER_THRESHOLD = 3
DEFAULT_AWOX_MIN_VICTIM_VALUE = Decimal("10000000")
DEFAULT_AWOX_BLUE_SCOUTING_BONUS = 15

# EVE Online inventory group IDs used for awox classification.
WARP_SCRAMBLER_GROUP_ID = 52  # contains both warp scramblers and warp disruptors
WARP_DISRUPT_FIELD_GENERATOR_GROUP_ID = 899  # HIC infinipoint module
HEAVY_INTERDICTOR_CRUISER_GROUP_ID = 894  # HIC ship hulls
SMARTBOMB_GROUP_ID = 374  # kept for reference; crossfire exclusion is generalized
CAPSULE_GROUP_ID = 29  # pods, exempt from throwaway-ship exclusion

AWOX_TACKLE_MODULE_GROUPS = {WARP_SCRAMBLER_GROUP_ID, WARP_DISRUPT_FIELD_GENERATOR_GROUP_ID}
THROWAWAY_VICTIM_SHIP_GROUPS = {237, 31}  # corvettes, shuttles
AWOX_SUPER_CAPITAL_GROUPS = {30, 659}  # titan, supercarrier
AWOX_HIGH_VALUE_VICTIM_GROUPS = {513, 902, 538}  # freighter, jump freighter, industrial
AWOX_SCORE_CAP = 90
